version: '3'
services:
  keycloak:
    image: jboss/keycloak:12.0.1
    container_name: keycloak
    ports:
    - 18080:8080
    volumes:    
    - ../../../target/keycloak-two-step-login-with-code.jar:/opt/jboss/keycloak/standalone/deployments/keycloak-two-step-login-with-code.jar   
    - ./realm.json:/opt/jboss/keycloak/imports/realm.json
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: keycloak
      KEYCLOAK_IMPORT: /opt/jboss/keycloak/imports/realm.json
    networks:
    - testnet

  maildev:
    container_name: maildev
    image: djfarrelly/maildev:1.0.0
    ports:
    - "1080:80"
    - "1234:25"
    networks:
    - testnet

networks:
  testnet:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.18.0.0/16
  
  
